config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'flashcards#home'
  get '/flashcards/:id/answer', to: "flashcards#answer", as: "flashcards_answer"
  get '/flashcards/:id/next', to: "flashcards#next", as: "flashcards_next"
  get '/flashcards/:id/previous', to: "flashcards#previous", as: "flashcards_previous"

  resources :flashcards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
  validates :prompt, presence: true, length: { minimum: 2 }
  validates :answer, presence: true, length: { minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  before_action :set_params, only: [:answer, :edit, :update, :show, :destroy]

  def home
  end

  def index
    @flashcards = Flashcard.all
  end

  def show
    # @flashcard = Flashcard.find(params[:id])
  end

  def next
    current_id = params[:id]
    next_id = Flashcard.where("id > ?", current_id.to_i).first
    if next_id === nil
      next_id = Flashcard.first
      redirect_to controller: :flashcards, action: :show, id: next_id
      # redirect_to flashcards_path(@flashcard(params[:next_id]))
      return
    end
      redirect_to controller: :flashcards, action: :show, id: next_id
  end

  def previous
    current_id = params[:id]
    previous_id = Flashcard.where("id < ?", current_id.to_i).last
    if previous_id === nil
      previous_id = Flashcard.last
      redirect_to controller: :flashcards, action: :show, id: previous_id
    return
  end
    redirect_to controller: :flashcards, action: :show, id: previous_id
  end

  def answer
  end

  def new
    @flashcard = Flashcard.new
  end

  def create
    @flashcard = Flashcard.new(f_params)
    if @flashcard.save
      redirect_to flashcard_path(@flashcard)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @flashcard.update(f_params)
      redirect_to flashcard_path(@flashcard)
    else
      render :edit
    end
  end

  def destroy
    @flashcard.destroy
    redirect_to flashcards_path
  end

  # def match(params[:guess])
  #   count = 0
  #   # User inputs a possible definition (guess in textarea)
  #   # Program checks if input matches the word definition
  #   if guess === @flashcard.answer
  #     # If yes, point counter increases and flashcard is set as know by the user, etc.
  #     # i am missing a count variable in the flashcards??
  #     @flashcard.count += 1
  #   end
  # end

  private
  def f_params
    params.require(:flashcard).permit(:prompt, :answer)
  end

  def set_params
    @flashcard = Flashcard.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/views/flashcards/answer.html.erb
<div class="card">
  <div class="card-body">
    <h1 class="title"><%= @flashcard.prompt %></h1>
    <h1 class="title-answer"><%= @flashcard.answer %></h1>
  </div>
</div>

<%= link_to "Back", flashcard_path(@flashcard), class: 'btn flash back btn-dark' %>

app/views/flashcards/edit.html.erb
<div class="form">
  <h4>Edit Flashcard</h4>
  <%= simple_form_for @flashcard do |f| %>
    <%= f.input :prompt %>
    <%= f.input :answer %>
    <%= f.button :submit, class: 'btn flash btn-dark'%>
  <% end %>
</div>
<%= link_to "Back", flashcards_path, class: 'btn flash back btn-dark' %>

app/views/flashcards/home.html.erb
<h1>Word's Up</h1>
<p>Let's test your memory by creating <span class="title-span">flashcards</span><br> with the <span class="title-span">new words</span> you learned today</p>
<!-- link to add a new flashcard
link to play flashcards -->

app/views/flashcards/index.html.erb
<div class="card-container">
  <h1 class="flashcards mt-2">Flashcards</h1>
  <%= link_to "Add a Card",  new_flashcard_path, class: 'btn flash add-plus btn-dark mb-3' %>

    <div class="row">
      <% @flashcards.each do |f| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="card-flashcard">
          <div class="card-prompt">
            <h2><%= link_to f.prompt, flashcard_path(f) %></h2>
            <div class = "card-destroy">
                <%= link_to flashcard_path(f), method: :delete, data: { confirm: "Are you sure?"} do %>
                <i class="fas fa-trash"></i>
                <% end %>
                <%= link_to edit_flashcard_path(f) do %>
                <i class="fas fa-edit"></i>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flashcards/new.html.erb
<div class="form">
  <%= simple_form_for @flashcard do |f| %>
    <%= f.input :prompt %>
    <%= f.input :answer %>
    <%= f.button :submit, class: 'btn flash btn-dark'%>
  <% end %>
</div>
<%= link_to "Back", flashcards_path, class: 'btn flash back btn-dark' %>

app/views/flashcards/show.html.erb
<div class="card">
  <div class="card-body">
    <!-- missing: show flashcards in order of % correct -->
    <h1 class="title"><%= @flashcard.prompt %></h1>
    <div class="input">
    <textarea name="guess" id="guess" cols="30" rows="5"></textarea>
    <!-- missing: compare guess with answer (JS) -->
    </div>
    <%= link_to "Previous", flashcards_previous_path, class: 'btn flash btn-dark' %>
    <%= link_to "Answer", flashcards_answer_path, class: 'btn flash btn-dark' %>
    <%= link_to "Next", flashcards_next_path, class: 'btn flash btn-dark' %>
  </div>
</div>

<%= link_to "Back", flashcards_path, class: 'btn flash back btn-dark' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcardsdictionary</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>